<?php

/** @var Dnd\SpecialOfferDisplayer\Block\OfferFrontBlock $block */
/** @var Magento\Framework\Escaper $escaper */

$specialOffers = $block->getSpecialOffers();

if ($specialOffers && $block->isSpecialOfferDisplayerEnabled()) : ?>
    <div class="offers-container">
        <div class="offers-container__slider" id="offers-container__slider"
             data-item-count="<?= count($specialOffers) ?>"
             data-item-displayed="0"
             data-sliding-delay="<?= $block->getSlidingDelay() ?>"
        >
            <?php foreach ($specialOffers as $key => $specialOffer) : ?>
                <div class="offers-container__offer item">
                    <div class="offers-container__offer-inner">
                        <div class="offers-container__offer-inner__image">
                            <img src="<?= $specialOffer->getImageFileName() ?>"
                                 alt="<?= $specialOffer->getOfferLabel() ?>"
                                 title="<?= $specialOffer->getOfferLabel() ?>"
                            />
                        </div>
                        <div class="offers-container__offer-inner__content">
                            <?= $specialOffer->getContent() ?>
                        </div>
                        <div class="offers-container__offer-inner__link">
                            <a href="<?= $escaper->escapeHtml($specialOffer->getRedirectionLink()) ?>"
                               class="button action secondary"
                               title="<?= __('Learn more') ?>"><?= __('Learn more') ?></a>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>

    <script type="text/x-magento-init">
    {
        "#offers-container__slider": {
            "Dnd_SpecialOfferDisplayer/js/offer-slider": {}
        }
    }
    </script>
<?php endif ?>


